### ISSUE TITLE
baseline_ft版本分类结果全部为相同的值

### ISSUE THREAD

**Issue by cherrysherryplus** [uyzhang/JCLIP#2]
运行baseline之后，结果正常，且分类结果符合视觉感受；但是运行baseline_ft之后，所有测试图片的分类结果的前5个类别ID，都是相同的值，如下图所示。
![image](https://github.com/uyzhang/JCLIP/assets/40523189/169b371b-baff-47f5-bbcb-333d83b828eb)

**Comment by uyzhang** [comment]
我们这边测试没有问题，请检查是不是scikit-learn这个框架是不是安装的有问题。

**Comment by cherrysherryplus** [comment]
好的，请问你使用的`scikit-learn`版本是多少呢？另外，我这边换了一下LogisticRegression的solver参数变成`solver="sag"`可以收敛了，但是使用默认的`solver="lbfgs"`还是会有问题。
